services:
    database:
      image: mongo
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: devops_db
      expose:
        - "27017"
      restart: always
      volumes:
        - /home/mount/data:/data
    api:
      build:
        context: ./backend
        dockerfile: dockerfile
      environment:
        DB_PORT: 27017
        PORT: 3000
        DB_NAME: database
        DB_USER: root
        DB_PASSWORD: root
        MONGO_URL: mongodb://database:27017
      depends_on:
        - database
      ports:
        - 3000:3000
      volumes:
        - ./backend:/app

    frontend:
      build:
        context: ./frontend
        dockerfile: dockerfile
      ports:
        - 8080:80
      expose: 
        - "8080"
      volumes:
        - ./frontend:/src
        - nodemodules:/src/node_modules

volumes:
  nodemodules: {}

