services:
    database:
      image: mongo
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: devops_db
      expose:
        - "27017"
      restart: always
      volumes:
        - /home/mount/data:/data
    api:
      build:
        context: ./backend
        dockerfile: dockerfile
      environment:
        DB_PORT: 27017
        PORT: 5000
        DB_NAME: database
        DB_USER: root
        DB_PASSWORD: root
        MONGO_URL: mongodb://root:root@database:27017
      depends_on:
        - database
      ports:
        - 5000:5000
      volumes:
        - ./backend:/app
    frontend:
      build:
        context: ./frontend
        dockerfile: dockerfile
      ports:
        - 80:80
      volumes:
        - ./frontend:/src
        - nodemodules:/src/node_modules
    prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
      ports:
        - 9090:9090
      command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
      depends_on:
        - db-exporter
        - api
    db-exporter:
      image: bitnami/mongodb-exporter:latest
      environment:
        - MONGODB_URI=mongodb://root:root@database:27017
      ports: 
        -  9216:9216



volumes:
  nodemodules: 
  prometheus-data:

