env:
  es2021: true
  node: true
extends:
  - google
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  object-curly-spacing: ["error", "always"],
  linebreak-style: ["off"],
  arrow-parens: ["off"],
  space-before-function-paren: ["error", {
    anonymous: "never",
    named: "never",
    asyncArrow: "always",
  }],
}