name: Backend_CI

on:
  push:
    # paths: [ backend/** ]

  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    env: 
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install dependencies
      run: |
        cd ./backend
        npm ci
    - name: Run Build
      run: |
        cd ./backend
        npm run build --if-present
    # - name: Run Test
    #   run: |
    #     cd ./backend
    #     npm test
    - name: Run Eslint
      run: |
        cd ./backend
        npm run lint

    #Whatever I tried, couldn't get this to work

    - name: Jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        threshold: 70
        working-directory: ./backend

    #This also didn't work, << Bad Credentials
    # uses: pomekhin/jest-github-action@1.1.5
    # env:
    #   GITHUB_TOKEN: ${{secrets.TOKEN}}
    # with:
    #   working-directory: "backend"
